# Generated by Django 3.0.5 on 2020-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0002_load_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='platform',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
