# Generated by Django 3.0.5 on 2020-05-03 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0003_auto_20200501_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('key', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
