# Generated by Django 3.0.5 on 2020-05-03 14:01

import cdzstat.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0004_sessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='entry_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='key',
            field=models.CharField(default=cdzstat.utils.rand_symbols, max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='loading',
            field=models.IntegerField(help_text='Measure in milliseconds. Start: responseStart, End: responseEnd', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='processing_time',
            field=models.IntegerField(help_text='Measure in milliseconds. Start: domLoading End: domComplete', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='referer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referer', to='cdzstat.Path'),
        ),
        migrations.AddField(
            model_name='request',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.SessionData'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.Browser'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='browser_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.UserLang'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='color_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.ColorParam'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.IpAddress', verbose_name='Ip address'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.ScreenSize'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='system_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.SystemInfo'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.TimeZone'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='ua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdzstat.UserAgent', verbose_name='User-Agent'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='window_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.WindowSize'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('session', 'key')},
        ),
        migrations.DeleteModel(
            name='UserParam',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ua',
        ),
    ]
