# Generated by Django 3.0.5 on 2020-05-15 08:49
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cdzstat', '0006_auto_20200503_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_point', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('processing_time', models.IntegerField(help_text='Measure in milliseconds. Start: domLoading End: domComplete', null=True)),
                ('loading', models.IntegerField(help_text='Measure in milliseconds. Start: responseStart, End: responseEnd', null=True)),
                ('external_referer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cdzstat.ExternalReferer')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.Host')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
            },
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='dt_create',
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='color_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cdzstat.ColorParam'),
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='ip',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='ip',
            field=models.ManyToManyField(null=True, to='cdzstat.IpAddress', verbose_name='Ip address'),
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='screen_size',
            field=models.ManyToManyField(blank=True, null=True, to='cdzstat.ScreenSize'),
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='window_size',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='window_size',
            field=models.ManyToManyField(blank=True, null=True, to='cdzstat.WindowSize'),
        ),
        migrations.RenameModel(
            old_name='Path',
            new_name='Node',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='transition',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.Node'),
        ),
        migrations.AddField(
            model_name='transition',
            name='referer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to='cdzstat.Node'),
        ),
        migrations.AddField(
            model_name='transition',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.SessionData'),
        ),
    ]
