# Generated by Django 3.0.5 on 2020-05-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0007_auto_20200515_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondata',
            name='system_info',
        ),
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('o', models.IntegerField(verbose_name='Order')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdzstat.Node')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdzstat.SessionData')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
