# Generated by Django 3.0.5 on 2020-05-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0008_auto_20200517_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacency',
            name='transition',
            field=models.ManyToManyField(to='cdzstat.Transition'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='system_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdzstat.SystemInfo'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='ip',
            field=models.ManyToManyField(to='cdzstat.IpAddress', verbose_name='Ip address'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='screen_size',
            field=models.ManyToManyField(to='cdzstat.ScreenSize'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='window_size',
            field=models.ManyToManyField(to='cdzstat.WindowSize'),
        ),
    ]
