# Generated by Django 3.0.5 on 2020-05-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdzstat', '0010_auto_20200517_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiondata',
            old_name='browser_lang',
            new_name='user_lang',
        ),
    ]
